name: blank_sample_project
description: Sample Project Structure

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.0.1

  # Client
  dio: ^4.0.6

  # Data & Storage
  shared_preferences: ^2.0.13
  equatable: ^2.0.3

dev_dependencies:
  # Client Tracker
  alice: ^0.2.5

  # Generator
  build_runner:
  flutter_driver:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  # Test
  integration_test:
    sdk: flutter
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

