name: blank_sample_project
description: Sample Project Structure

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.0.1

  # Client
  dio: ^4.0.6

  # Data & Storage
  shared_preferences: ^2.0.13
  equatable: ^2.0.3

  # Media
  video_player: ^2.4.0

dev_dependencies:
  # Client Tracker
  alice: ^0.2.5

  # Generator
  build_runner:
  flutter_driver:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  # Test
  integration_test:
    sdk: flutter
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-SemiBold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf


